### ISSUE TITLE
node ssl_server.js & fails

### ISSUE THREAD

**Issue by jnewbery** [streamium/streamium#224]
I'm following the installation instructions from the README file, and I get to the following step:

```
node ssl_server.js &
```

which fails:

```
$ node ssl_server.js
module.js:338
    throw err;
          ^
Error: Cannot find module '<streamium_directory>/ssl_server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

should that instruction be:

```
node ssl_peerjs.js 
```

instead?

**Comment by aavella77** [comment]
I had the same problem.  I think the suggested change is correct.

**Comment by jnewbery** [comment]
There doesn't seem to be any activity on this repo. Closing
